@extends('templates.main')
@section('content')
@include('partials.intro')
@include('partials.about')
@include('partials.testimonial')
@include('partials.services_home')
@include('partials.team')
@include('partials.newsletter')
@endsection